### ISSUE TITLE
Memory Errors upon destroying swapchain

### ISSUE THREAD

**Issue by wkaelj** [wkaelj/SpiritRender#1]
Calling the spDestroySwapchain function causes memory errors, which change depending on the debugger.
I find the most common is a `free: double free or corruption`.
This error also seems to happen upon destroying a SpiritDevice. I think it has to do with my struct handling.

**Comment by wkaelj** [comment]
It was because i was creating swapchain with the size of a pointer to the swapchain
```
typedef struct t_SpiritSwapchain {
 // stuff
} *SpiritSwapchain;

...

SpiritSwapchain theSwapchain = malloc (sizeof (SpiritSwapchain)); // see the problem?

// fix
SpiritSwapchain theSwapchain = malloc (sizeof (struct t_SpiritSwapchain));
```
It is frustrating because I clearly knew when I wrote the device components, because I did it properly there.

**Comment by wkaelj** [comment]
BTW thanks to @beaumanvienna helping me find this!

**Comment by beaumanvienna** [comment]
You're welcome, buddy! :-D
